/**
 * Byte runs a Room Viewer plan is made of.
 *
 * GENERATED by `tools/build-plan-skeleton.ts` — do not edit by hand.
 *
 *   corpus   /Volumes/Prince/Roomviewer/Data
 *   sampled  400 of 1879 plans (390 carried a full skeleton)
 *   donor    Stage Design Idea for McGlohon Theater.rv4
 *   built    2026-07-31
 *
 * Two kinds of value live here and they are not equally well understood:
 *
 *   **Measurements.** Runs that were identical in every plan measured. The
 *   preamble, the container list header, the blocks that follow `RVRoom` and
 *   the second `RVRoomDef`, and the wall pen/brush block are all unanimous
 *   across 390 plans. These are findings, not choices.
 *
 *   **A donor.** `SETTINGS_BLOCK` is the 392-byte record an empty
 *   `RVRegion` carries: the plan's default chair and table, its name, and
 *   several hundred bytes nobody decoded — grid, scale, ceiling and layout
 *   defaults, which differ from plan to plan. There is no consensus value to
 *   compute, so one real plan's block is copied verbatim, exactly as
 *   `borrowStyle` and `borrowFont` copy pen and font blocks in
 *   `synthesize.ts`. The donor's own room name is stripped before committing,
 *   so no venue or event data is carried here; the three name fields are the
 *   only bytes `plan-skeleton.ts` ever authors inside the record.
 */

/* eslint-disable */

/** `COleDocument` writes three DWORDs before the first tag: 00 00 00 00 02 00 00 00 00 00 00 00. */
export const OLE_PREAMBLE = Buffer.from('000000000200000000000000', 'hex');

/**
 * A container's list header, at body +20: list version, a flag, a reserved
 * word. Groundplan used to write `1, 0, 0` here; every one of the
 * 92,230 containers measured writes `0, 1, 0`. The parser reads
 * neither word, which is why nothing caught it.
 */
export const CONTAINER_LIST_HEADER = Buffer.from('000001000000', 'hex');

/** Four document-level bytes that follow the empty `RVRoom` record. */
export const ROOM_FOLLOW = Buffer.from('02000000', 'hex');

/** Eighteen bytes the second `RVRoomDef` carries after its child count. */
export const ROOMDEF_TAIL = Buffer.from('030000000000000000000000000000000000', 'hex');

/** The undecoded pen/brush block (+26..+62) every wall segment carries. */
export const WALL_STYLE = Buffer.from('01000000010006000000280000002800000000000000010000000000ffffff0000000000', 'hex');

/** COLORREF the corpus stamps on wall segments, at +54. */
export const WALL_COLOR = 0x00ffffff;

/** Segment kind code for a wall line, at +20. */
export const WALL_KIND = 0;

/** Point count a wall line declares at +22. */
export const WALL_VERTEX_HINT = 2;

/** The int32 that opens the document trailer. */
export const TRAILER_LEAD = 1;

/**
 * The settings record an empty `RVRegion` holds, with the donor's room name
 * removed. Offsets below are into this buffer, and are the only positions any
 * code writes to.
 */
export const SETTINGS_BLOCK = Buffer.from('0100000000000b000000010000000100000001000000010000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000105374616e646172642031382278313822000000000065732d3852c1e03f00000000000000000080764001000000000000000000000000000000000000000000000000c0a24000000000000000000600000000000018b540030000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000083627207820313822000200000000000000000000000100000000000000000000000018b54000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000ffffff000100000002000000', 'hex');

/** Length byte of the default-chair name, "Standard 18"x18"". */
export const SETTINGS_CHAIR_AT = 106;

/** Length byte of the room name — zero-length as committed. */
export const SETTINGS_NAME_AT = 248;

/** Length byte of the default-table name, "6' x 18"". */
export const SETTINGS_TABLE_AT = 278;
